spring:
  application:
    name: bank-demo-was
  config:
    import:
      - classpath:application-log.yaml
      - classpath:application-core.yaml
      - classpath:application-was.yaml
      - classpath:application-adaptor.yaml
